application:
  auth:
    instance:
      hostname: localhost
eureka:
  client:
    service-url:
      defaultZone: http://${application.auth.instance.hostname}:5001/eureka
server:
  port: 5005
spring:
  application:
    name: auth
  redis:
    host: 94.191.98.99
    port: 6379
    database: 0
    password: llzguazi
    jedis:
      pool:
        max-active: 8
        min-idle: 0
  thymeleaf:
    prefix: classpath:/templates
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    cache: false
  security:
    user:
      name: user
      password: 123456
    strategy: com.llzguazi.auth.config.security.DefaultSecurityContextHolderStrategy

