application:
  auth:
    instance:
      hostname: localhost
eureka:
  client:
    service-url:
      defaultZone: http://${application.auth.instance.hostname}:5001/eureka
server:
  port: 5006
  servlet:
    session:
      timeout: 10
spring:
  application:
    name: gateway
  redis:
      host: 94.191.98.99
      port: 6379
      database: 0
      password: llzguazi
      jedis:
        pool:
          max-active: 8
          min-idle: 0
  session:
    store-type: redis
    redis:
      flush-mode: on-save
    namespace: spring:session
thymeleaf:
    cache: false




